
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
  redis:
    image: "redis"
    ports:
      - "6379:6379"